# Generated by Django 5.0.1 on 2024-01-12 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Nombre")),
                ("role", models.CharField(max_length=50, verbose_name="Rol")),
                ("image", models.ImageField(upload_to="team", verbose_name="Imagen")),
                (
                    "created",
                    models.DateField(
                        auto_now_add=True, verbose_name="Fecha de creacion"
                    ),
                ),
                (
                    "updated",
                    models.DateField(auto_now=True, verbose_name="Fecha de edicion"),
                ),
            ],
            options={
                "verbose_name": "miembro",
                "verbose_name_plural": "miembros",
            },
        ),
        migrations.CreateModel(
            name="Social",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, verbose_name="Nombre Red Social"),
                ),
                ("link", models.URLField(verbose_name="Enlace")),
                (
                    "created",
                    models.DateField(
                        auto_now_add=True, verbose_name="Fecha de creacion"
                    ),
                ),
                (
                    "updated",
                    models.DateField(auto_now=True, verbose_name="Fecha de edicion"),
                ),
                (
                    "members",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_links",
                        to="team.member",
                        verbose_name="Miembro",
                    ),
                ),
            ],
            options={
                "verbose_name": "red social",
                "verbose_name_plural": "redes sociales",
            },
        ),
    ]
