# Generated by Django 5.0.1 on 2024-01-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ServiceInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "years_of_experience",
                    models.IntegerField(verbose_name="Años de Experiencia"),
                ),
                (
                    "qualified_professionals",
                    models.IntegerField(verbose_name="Profesionales Calificados"),
                ),
                (
                    "total_products",
                    models.IntegerField(verbose_name="Productos Totales"),
                ),
                (
                    "daily_orders",
                    models.IntegerField(verbose_name="Pedidos Todos los Días"),
                ),
            ],
            options={
                "verbose_name_plural": "Información del Servicio",
            },
        ),
    ]
