# Generated by Django 5.0.1 on 2024-01-17 19:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="description",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(default=1, upload_to="category_images/"),
            preserve_default=False,
        ),
    ]
