# Generated by Django 5.0.1 on 2024-01-17 19:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_category_description_category_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="created",
            field=models.DateField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Fecha de creación",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="category",
            name="updated",
            field=models.DateField(auto_now=True, verbose_name="Fecha de edición"),
        ),
        migrations.AddField(
            model_name="product",
            name="created",
            field=models.DateField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Fecha de creación",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="updated",
            field=models.DateField(auto_now=True, verbose_name="Fecha de edición"),
        ),
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(verbose_name="Descripción"),
        ),
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(
                upload_to="category_images/", verbose_name="Imagen"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Nombre"),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="products.category",
                verbose_name="Categoría",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(verbose_name="Descripción"),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(upload_to="product_images/", verbose_name="Imagen"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Nombre"),
        ),
        migrations.AlterField(
            model_name="product",
            name="price_range",
            field=models.CharField(
                help_text="Price range, e.g., $11 - $99",
                max_length=20,
                verbose_name="Rango de precio",
            ),
        ),
    ]
